export const FETCH_MODELS = 'FETCH_MODELS';
export const FETCH_MODELS_SUCCESS = 'FETCH_MODELS_SUCCESS';
export const FETCH_MODELS_FAILED = 'FETCH_MODELS_FAILED';

export const FETCH_MODEL_ENGINE = 'FETCH_MODEL_ENGINE';
export const FETCH_MODEL_ENGINE_SUCCESS = 'FETCH_MODEL_ENGINE_SUCCESS';
export const FETCH_MODEL_ENGINE_FAILED = 'FETCH_MODEL_ENGINE_FAILED';

export const FETCH_COLORS = 'FETCH_COLORS';
export const FETCH_COLORS_SUCCESS = 'FETCH_COLORS_SUCCESS';
export const FETCH_COLORS_FAILED = 'FETCH_COLORS_FAILED';

export const FETCH_SUMMARY = 'FETCH_SUMMARY';
export const FETCH_SUMMARY_SUCCESS = 'FETCH_SUMMARY_SUCCESS';
export const FETCH_SUMMARY_FAILED = 'FETCH_SUMMARY_FAILED';